## -----------------------------------------------
## Basic Configuration
## -----------------------------------------------

title = "Forest Ecophysiology"
copyright = "2024"

## -----------------------------------------------
## Publish
## -----------------------------------------------

relativeURLs = "true"
#canonifyURLs = "true"

# Local
baseURL = "https://gevargu.github.io/"
publishDir = "public"

# Remote
#baseURL = "https://caressofsteel.github.io/demos/hugo/hugo-story/"
#publishDir = "//centos/sites/hugodev/hugostory/"

## -----------------------------------------------
## Hugo Built-in Features
## -----------------------------------------------

disableKinds = ["taxonomy", "taxonomyTerm", "section"]
# googleAnalytics = "G-XXXXXXXXXX"

## -----------------------------------------------
## Site Parameters
## -----------------------------------------------

[Params]
  description = "Studying plant ecophysiology at OSU"
  logo = "blog/public/leaf_logo.png"
  favicon = true

[Params.social]
  github = "https://github.com/gevargu/"
  email = "vargasgg@oregonstate.edu"

[Params.asset]
  fontawesome_css = ["css/fontawesome-all.min.css"]
  fontawesome_js = ["js/fontawesome-all.min.js"]