## -----------------------------------------------
## Basic Configuration
## -----------------------------------------------

title = "Forest Ecophysiology"
languageCode = "en-us"
copyright = "2024"

# Define the content directory
contentDir = "content"

# Define the layout directory
layoutDir = "layouts"

# Define the data directory
dataDir = "data"

# Define the static files directory
staticDir = "static"

# Define the output directory
publishDir = "public"

# Enable sections to create separate pages
[permalinks]
  posts = "/:year/:month/:title/"
  # Add more sections as needed

[outputFormats]
  [outputFormats.HTML]
    baseName = "index"

## -----------------------------------------------
## Publish
## -----------------------------------------------

relativeURLs = "true"
#canonifyURLs = "true"

# Local
baseURL = "https://gevargu.github.io/"
publishDir = "public"

## -----------------------------------------------
## Hugo Built-in Features
## -----------------------------------------------

disableKinds = ["taxonomy", "taxonomyTerm", "section"]
# googleAnalytics = "G-XXXXXXXXXX"

## -----------------------------------------------
## Site Parameters
## -----------------------------------------------

[Params]
  description = "Studying plant ecophysiology at OSU"
  logo = "./leaf_logo.png"
  favicon = true

[Params.social]
  github = "https://github.com/gevargu/"
  twitter = "https://twitter.com/tropicalecophys"
  email = "vargasgg@oregonstate.edu"

[Params.asset]
  fontawesome_css = ["css/fontawesome-all.min.css"]
  fontawesome_js = ["js/fontawesome-all.min.js"]